### ISSUE TITLE
Adds ability to unsign cookies via request

### ISSUE THREAD

**Issue by vatson** [fastify/fastify-cookie#100]
## 🚀 Feature Proposal

Adds ability to unsign cookies via request.

## Motivation

- In this case, the request becomes self-sufficient and there is no need to pass reply as an argument to other methods.
- NestJS allows to inject only request object to the constructor of Request scoped services. This is logical because services should not compose a reply. It should be done in other layers (controllers, interceptors)

## Example

```
fastify.get('/', (req, reply) => {
  const mySecretCookie = req.unsignCookie(req.cookies.mySecretCookie);
  reply
    .setCookie('mySecretCookie', 'value', {
      path: '/',
      signed: true
    })
    .send({ hello: 'world' })
})

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
