### ISSUE TITLE
Most basic functionality not working

### ISSUE THREAD

**Issue by additop78** [fastify/fastify-cookie#140]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.18.1

### Plugin version

5.3.1

### Node.js version

12

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.10

### Description

The most basic functionality as shown in the intro docs is not working even after spending some 2 hours trying to figure things out. Please make documentation more elaborate if possible. 

### Steps to Reproduce

No specific case. The steps in the docs itself don't work. The cookie is not set.

### index.js

```js
fastify.register(require('fastify-cookie'), {
   secret: 'xyz',
   parseOptions: {}
})
```

### in my route handler
```js
reply
   .code(200)
   .cookie('foo', 'bar')
   .send({message: 'Hello world'})
```

### Expected Behavior

The desired cookie should be set.

**Comment by kibertoad** [comment]
Could you create a failing test for your use-case? Fairly sure there are existing tests for main flow.

**Comment by jsumners** [comment]
Note that cookies set on local host don't really work in most browsers. Particularly Chrome. You should use a "real" domain. Even if it's something like ngrok.

**Comment by additop78** [comment]
I'm aptly sure that there are tests for the main flow. I'm not questioning the integrity of the package. It's just that I feel there are some hideous catches as jsummers highlighted which should be specified in docs.

**Comment by mcollina** [comment]
This is probably relevant: https://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain

Would you like to send a PR that improves our docs?

**Comment by additop78** [comment]
Thanks everyone.
