### ISSUE TITLE
Setting a specific path via the options argument isn't applied.

### ISSUE THREAD

**Issue by contis2908** [fastify/fastify-cookie#16]
**Example:**
1. `res.setCookie('language', 'en', { path:'/foo' });`
2. `res.setCookie('language', 'en', { path:'/' });`

**Expected outcome:**
1. Name `language` value `en` path `/foo`
2. Name `language` value `en` path `/`

**Actual outcome:**
1. No cookie is getting set at all.
2. Default path is taken

Tested in Chrome Version 67.0.3396.99
Node version v11.0.0
Fastify-Cookie Version 2.1.1

**Comment by cemremengu** [comment]
Could you please share a reproducible sample? The tests for this are [passing](https://github.com/fastify/fastify-cookie/blob/master/test/cookie.test.js#L10)

**Comment by contis2908** [comment]
I just did some further digging and I believe what is happening is that the path is actually set as I can see the Response Cookie in the Browser. However, Chrome is not setting the Cookie so the problem isn't on your side.

**Comment by cemremengu** [comment]
Right, thats probably the issue. I think we can update our docs adding a note for this. Can you verify if that solves it for you?

**Comment by contis2908** [comment]
Well to be honest I was about to close that issue again as it mysteriously vanished on my side.
I will be checking up on it tomorrow again and post updates here.

Although, I think reminding users about this might be a good idea either way.

**Comment by jsumners** [comment]
If you are attempting to set the cookie on a `localhost` domain then you will encounter difficulties, particularly with Chrome based browsers.

**Comment by contis2908** [comment]
@jsumners I did read about this in one of the stack links i've posted above. However, I encountered the issue earlier today in our production repods.io.

As mentioned I am unable to reproduce it again and as it seemed it wasn't related to your side.
Thanks for the quick support, will be closing that issue for now
