### ISSUE TITLE
Add type definitions for parseOptions in FastifyCookieOptions

### ISSUE THREAD

**Issue by MoSheikh** [fastify/fastify-cookie#161]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently, `parseOptions` is not defined under `FastifyCookieOptions`. I was hoping to change the `FastifyCookieOptions` interface to the following:
```ts
// plugin.d.ts

export interface FastifyCookieOptions {
  secret?: string | string[];
  parseOptions?: CookieSerializeOptions;
}
```
And add the following test:
```ts
// test/plugin.d.ts

const appWithParserOptions = fastify();

const parseOptions: fastifyCookieStar.CookieSerializeOptions = {
  domain: "example.com",
  encode: (value: string) => value,
  expires: new Date(),
  httpOnly: true,
  maxAge: 3600,
  path: "/",
  sameSite: "lax",
  secure: true,
  signed: true,
};
expectType<fastifyCookieStar.CookieSerializeOptions>(parseOptions);

appWithParserOptions.register(cookie, {
  secret: "testsecret",
  parseOptions,
});
appWithParserOptions.after(() => {
  server.get("/", (request, reply) => {
    const { valid, renew, value } = reply.unsignCookie(request.cookies.test);

    expectType<boolean>(valid);
    expectType<boolean>(renew);
    expectType<string | null>(value);
  });
});

```

**Comment by mcollina** [comment]
Thanks! Would you like to send a Pull Request to address this issue?

**Comment by MoSheikh** [comment]
Sure! I did try pushing a branch through but it gave me a `Permission Denied` error - would I need to be added as a contributer?

**Comment by mcollina** [comment]
You'll need to fork the project first, take a look at https://www.google.com/amp/s/www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/amp/

**Comment by MoSheikh** [comment]
@mcollina Oh right - thank you! [Here's the PR](https://github.com/fastify/fastify-cookie/pull/162).
