### ISSUE TITLE
Payload typing lost when using setCookie before

### ISSUE THREAD

**Issue by hugoattal** [fastify/fastify-cookie#166]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

5.5.0

### Node.js version

16.13.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11 (21H2)

### Description

When using a schema for my route, I get payload typing. But when I use `setCookie` on my reply, the payload get the type `unknown`.

![image](https://user-images.githubusercontent.com/4563971/153012232-0c0b6847-bd24-42d5-9528-ca2e3bac445a.png)
![image](https://user-images.githubusercontent.com/4563971/153012146-ad765599-4f27-4db8-96ca-b9a3c630065c.png)

### Steps to Reproduce

```ts
type TSchemaResponse = {
    message: string
};

// ...
fastifyInstance.post<Response: TSchemaResponse>(
    "/hello",
    (request, reply) => {
        reply.send({message: 123}); // typescript error as message should be a string
    }
);
// ...
```

```ts
type TSchemaResponse = {
    message: string
};

// ...
fastifyInstance.post<Response: TSchemaResponse>(
    "/hello",
    (request, reply) => {
        reply
            .setCookie("hello", "there")
            .send({message: 123}); // no error (there should be an error)
    }
);
// ...
```

### Expected Behavior

The payload should still be typed after calling setCookie (as setCookie should return "this" type)

**Comment by mcollina** [comment]
@fastify/typescript

**Comment by hugoattal** [comment]
Hum, are you suggesting I should have post this issue in another repo?
If so, I'm sorry, I don't want to waste your time 😅... But I didn't find such repo 😕...

And the type definitions seems to be in this very repo:
https://github.com/fastify/fastify-cookie/blob/master/plugin.d.ts

**Comment by darkgl0w** [comment]
@hugoattal > I will take a look at this. Can you please provide a GitHub repo with a minimal setup reproducing this issue so I can just clone it ?

**Comment by hugoattal** [comment]
@darkgl0w Here it is: https://github.com/hugoattal/fastify-cookie-typing-bug-repro

Just run `pnpm install` (should also work with npm) and you can see the error under `src/handler.ts`

![image](https://user-images.githubusercontent.com/4563971/153067243-1dbfefcc-d2a6-44af-be4a-ac51c6579d33.png)

**Comment by darkgl0w** [comment]
@hugoattal > thank you for the minimal reproducible example.

Thanks to this I was able to spot the cause of this issue.
I will submit a PR to resolve this issue in a moment :)
