### ISSUE TITLE
The "latest" tag on npm is currently pointing to v5.5.0

### ISSUE THREAD

**Issue by joelmukuthu** [fastify/fastify-cookie#168]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.2

### Plugin version

5.6.0

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

It should be pointing to the latest version `5.6.0`, no?

### Steps to Reproduce

```
$ npm info fastify-cookie

-- removed for brevity --

dist-tags:
latest: 5.5.0  next: 5.6.0    
```

### Expected Behavior

```
$ npm info fastify-cookie

-- removed for brevity --

dist-tags:
latest: 5.6.0
```

**Comment by mcollina** [comment]
my bad, will fix asap

**Comment by mcollina** [comment]
done
