### ISSUE TITLE
Exported types do not support using HTTP2

### ISSUE THREAD

**Issue by allancalix** [fastify/fastify-cookie#17]
The plugin type exported here expects only HTTP underlying types while Fastify itself supports both HTTP and HTTP2 types.

This package seemingly works with either and can safely expect either one.

**Comment by cemremengu** [comment]
Typings are mostly based on community contributions so those might be missing unfortunately. Would you like to send a PR?

**Comment by allancalix** [comment]
No problem!

Submitted a PR here: https://github.com/fastify/fastify-cookie/pull/18
