### ISSUE TITLE
Request Cookies Should Be Typed As `string | undefined`

### ISSUE THREAD

**Issue by rag4214** [fastify/fastify-cookie#189]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

6.0.0

### Node.js version

16.15.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11 Pro Build 22000.739

### Description

Right now when using the package any cookie is always typed as a string when it could be undefined.

Pretty simple fix, just changing the type from `cookies: { [cookieName: string]: string };` to `cookies: { [cookieName: string]: string | undefined };`

(if you wanted to make it more TypeScript-y you could do `cookies: Record<string, string | undefined>;`

### Steps to Reproduce

```ts
fastify.get('/', async (reqeust, reply) => {
  const { someCookieThatDoesNotExist } = request.cookies; // someCookieThatDoesNotExist: string
  console.log(someCookieThatDoesNotExist); // undefined
  console.log(typeof someCookieThatDoesNotExist); // undefined
  
  return { hello: 'world' }
});
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
