### ISSUE TITLE
Fastify-plugin - expected '^1.1.0' fastify version, '2.0.0' is installed

### ISSUE THREAD

**Issue by BofEmptiness** [fastify/fastify-cookie#19]
After update to fastify 2.0 i've got an error from this plugin. Is there a way to fix this?

**Comment by cemremengu** [comment]
You need to get the `@next` release to use this plugin with Fastify v2

**Comment by cemremengu** [comment]
Sorry my bad

**Comment by BofEmptiness** [comment]
Ok, so i will edit this in source code and wait until new npm package will come?

**Comment by cemremengu** [comment]
@BofEmptiness landed in `^2.1.5`
