### ISSUE TITLE
[Testing] [fastify-cookie] How to get generated signed cookie for inject

### ISSUE THREAD

**Issue by budarin** [fastify/fastify-cookie#191]
It is necessary to generate the signed cookie content for the tests

How can I get it as a string in tests to insert into the invocation of the inject method?

Maybe the plugin should explicitly export the sign and unsign functions?

**Comment by mcollina** [comment]
Transferred. Would you like to send a PR?

**Comment by simoneb** [comment]
@budarin have you considered doing an HTTP request which generates the cookie and after that use the cookie in the following requests?

**Comment by budarin** [comment]
> Transferred. Would you like to send a PR?

I'll try

**Comment by budarin** [comment]
> @budarin have you considered doing an HTTP request which generates the cookie and after that use the cookie in the following requests?

I didn't quite understand the idea - explain in more detail what you want to implement

**Comment by simoneb** [comment]
@budarin did you manage to make any progress on this?

**Comment by budarin** [comment]
> I assume you want to generate a cookie because your app requires it, so I guess your app also has a way to generate that cookie and send it to the client, right? If my assumption is right, if you hit the endpoint that generates the cookie using fastify.inject then you can grab it from the headers and use it in your next fastify.inject without having to generate one manually

I need to check that a request without a signed cookie does not pass - the service should not accept a request without a signed cookie.

A signed cookie is issued by another service - so I need to generate a signed cookie in some way before accessing the service

**Comment by simoneb** [comment]
The best way to validate your approach and get the team to approve of it is to submit a PR with that change so we can see what it'd look like. Is it something you'd be happy to do?

**Comment by budarin** [comment]
Have found wrong type definition in last release - mede fix
