### ISSUE TITLE
Secret should accept a Buffer (or array of buffers)

### ISSUE THREAD

**Issue by pluma** [fastify/fastify-cookie#214]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

The type validation for `secret` in the plugin config and the signer implementation should be modified to allow `secret` to also be a `Buffer` instead of a `string`. This would mean modifying the checks for `typeof secret` to be expanded to also check `Buffer.isBuffer`.

### Motivation

The signer implementation already uses `crypto.randomBytes`, which returns a `Buffer`, to validate the algorithm. When generating secrets dynamically it would be useful to be allowed to simply pass the `Buffer` directly instead of having to convert it to a string representation like hex or base64 first.

### Example

```js
const secret = crypto.randomBytes(32); // new secret on every restart
app.register(require("@fastify/cookie"), { secret });
```

**Comment by Uzlopak** [comment]
PR is welcome

**Comment by pluma** [comment]
This could be extended to also allow crypto keys but I have no idea how asymmetric key pairs would be handled or how to even validate keys or any of the other data types `createHmac` supports as a secret, so I think that would be out of scope.

**Comment by Uzlopak** [comment]
If you implement asymmetrical encryption than basically fastify-secure-session would be obsolete.

**Comment by pluma** [comment]
Yeah, now that I think about it, supporting (as)symmetric keys would make more sense for encrypting rather than signing the cookie. I think it would make more sense to keep encrpytion separate from signing so this should probably be a separate option. I'll write a feature request.
