### ISSUE TITLE
The unit of `maxAge` is set in seconds, not msec

### ISSUE THREAD

**Issue by seia-soto** [fastify/fastify-cookie#219]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.7.0

### Plugin version

8.3.0

### Node.js version

v18.10.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6 (21G115)

### Description

The following is fastify-cookie option typing (truncated). However, unlike the description of `CookieSerializeOptions['maxAge']`, the actual value takes second(s) as its unit.

```ts
export interface CookieSerializeOptions {
  /**  A `number` in milliseconds that specifies the `Expires` attribute by adding the specified milliseconds to the current date. If both `expires` and `maxAge` are set, then `expires` is used. */
  maxAge?: number;
}
```

### Steps to Reproduce

I set the simple test environment: https://github.com/seia-soto/fastify-cookie-maxage

```ts
fastify.get('/set', async (_req, reply) => {
  reply.setCookie('test', '1', {
    maxAge: 3600
  })
})
```

### Expected Behavior

If the unit is msec, we should see 3.6ss instead of a hour below: (LibreWolf)

![image](https://user-images.githubusercontent.com/30369714/198352355-1a20831d-7e2f-48f7-966f-ca20ab26b445.png)

This is not the browser specific issue: (Safari)

![image](https://user-images.githubusercontent.com/30369714/198353105-c7726d73-9589-446b-8b1d-9f2ba51df679.png)

**Comment by seia-soto** [comment]
Using second for max-age is a common behavior and I think we can just update the type definition instead of fixing this.

**Comment by Uzlopak** [comment]
It would be nice if you would provide a PR

**Comment by seia-soto** [comment]
Done 🙃
