### ISSUE TITLE
v5.3.0 breaks setting signed cookie on the response with Cannot read properties of undefined (reading 'sign')"

### ISSUE THREAD

**Issue by Tirke** [fastify/fastify-cookie#227]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

\>= 5.3.0

### Node.js version

Tested on 19.x, 18.x and 16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Tested on both macOS and Linux. macOs is 13.1 (22C65). Linux is ubuntu node:16-bullseye-slim.

### Description

Please refer to fastify/fastify-secure-session#174 if you need more context
When setting signed cookie in the response using fastify-secure-session >= 5.3.0
```
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Cannot read property 'sign' of undefined"
}
```

Using fastify-secure-session,@5.2.0 no error is thrown.
Setting signed to false will also prevent the issue.

### Steps to Reproduce

I'm reusing the snippet done by @wilkmaia in the previous issue and just adding the setCookie call.

```
const Fastify = require('fastify');
const secureSession = require('@fastify/secure-session');
const {DateTime} = require('luxon');

const run = async () => {
  const app = Fastify();

  await app.register(secureSession, {
    secret: 'averylogphrasebiggerthanthirtytwochars',
    salt: 'mq9hDxBVDbspDR6n',
  });

  app.post('/', (request, reply) => {
    request.session.set('data', request.body);
    reply.setCookie('my-session', 'idSession', {
      expires: DateTime.now().plus({weeks: 2}).toJSDate(),
      httpOnly: true,
      secure: true,
      domain: 'test.com',
      sameSite: 'none',
      maxAge: 3600,
      signed: true,
      path: '/',
    });
    reply.send('session set');
  });

  app.get('/', (request, reply) => {
    const data = request.session.get('data');
    if (!data) {
      reply.code(404).send();
      return;
    }
    reply.send(data);
  });

  app.get('/all', (request, reply) => {
    // get all data from session
    const data = request.session.data();
    if (!data) {
      reply.code(404).send();
      return;
    }
    reply.send(data);
  });

  app.listen({port: 3000});
};

run()
```

### Expected Behavior

I think this is a valid use case that should still work in versions >= 5.3.0.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Lokkve0126** [comment]
Thank you ,Has the issue been fixed？

**Comment by Lokkve0126** [comment]
Lines 206 through 213 in @fastify/secure-session/index.js determine whether the @fastify/cookie plug-in has been registered.
When we register @fastify/secure-session directly in the main.ts file and pass in the configuration items such as:

In this case, the code block goes to the else, and the fastify registration is passed back through the callback function @fastify/cookie plugin, Earlier I looked at the fastify registration process and found that the register accepts two parameters, the plugin,opts. Here we can see that no parameters were passed when the @fastify/cookie plugin was passively registered.
Finally, when our registration process came to the @fastify/cookie callback function, the incoming configuration parameter did not exist. As a result, the options received by the plugin function at the beginning of line 85 by @fastify/cookie/plugin.js was an empty object. As to why it was an empty object, In avvio/boot.js, you can see that opts are assigned to empty objects when use is handled internally. In this object values are undefined,signer in ternary operation judgment value secret is undefined, so call setCookie function when the incoming signer is undefined resulting in an error

```typescript
// @fastify/secure-session/index.js
if (fastify.hasPlugin('@fastify/cookie')) {
    fastify
      .register(fp(addHooks))
  } else {
    fastify
      .register(require('@fastify/cookie'))
      .register(fp(addHooks))
  }
```
```typescript
//registry @fastify/secure-session options
{
    logLevel: "debug",
    sessionName: 'sessionServer',
    cookieName: 'session-cookie',
    key: fs.readFileSync(path.resolve(__dirname, "../../secret-key")).slice(0, 32),
    secret: fs.readFileSync(path.resolve(__dirname, "../../secret-key")).slice(0,32),
    salt: process.env.salt,
    cookie: {
      secure: true,
      path: "/",
      maxAge: 60000,
      sameSite: true,
      signed : true,
    }
  }
```
```typescript

function plugin(fastify, options, next) {
  //options = {}
  const secret = options.secret; //undefined
  const hook = getHook(options.hook);
  if (hook === undefined) {
    return next(new Error('@fastify/cookie: Invalid value provided for the hook-option. You can set the hook-option only to false, \'onRequest\' , \'preParsing\' , \'preValidation\' or \'preHandler\''));
  }
  const isSigner = !secret || (typeof secret.sign === 'function' && typeof secret.unsign === 'function');
  const algorithm = options.algorithm || 'sha256';
  const signer = isSigner ? secret : new Signer(secret, algorithm);//undefined

//.................other code


function setCookie(name, value, cookieOptions) {
    const opts = Object.assign({}, options.parseOptions, cookieOptions);
    return fastifyCookieSetCookie(this, name, value, opts, signer);//signer undefined
 }
}

function fastifyCookieSetCookie(reply, name, value, options, signer) {
  const opts = Object.assign({}, options);
  if (opts.expires && Number.isInteger(opts.expires)) {
    opts.expires = new Date(opts.expires);
  }

 //This will result in an error if the user cookie configuration item is signed
 //opts.signed === undefined 
  if (opts.signed) {
    value = signer.sign(value);
  }

  if (opts.secure === 'auto') {
    if (isConnectionSecure(reply.request)) {
      opts.secure = true;
    } else {
      opts.sameSite = 'lax';
      opts.secure = false;
    }
  }

  const serialized = cookie.serialize(name, value, opts);
  let setCookie = reply.getHeader('Set-Cookie');
  if (!setCookie) {
    reply.header('Set-Cookie', serialized);
    return reply;
  }

  if (typeof setCookie === 'string') {
    setCookie = [setCookie];
  }

  setCookie.push(serialized);
  reply.removeHeader('Set-Cookie');
  reply.header('Set-Cookie', setCookie);
  return reply;
}
```
