### ISSUE TITLE
Error registering fastify-cookie together with fastify-sessions

### ISSUE THREAD

**Issue by HellpMe** [fastify/fastify-cookie#234]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm trying to use fastify-session and some features of fastify-cookie, but when I register them the following error appears, "The dependency 'fastify-cookie' of plugin 'fastify-session' is not registered", but where I'm registering it's all correct, I'm pulling the other plugins without any difficulty, and I didn't find anything related about it.

``` typescript
import Fastify, { FastifyInstance } from "fastify";
import fastifyRateLimit from "@fastify/rate-limit";
import fastifySession from 'fastify-session';
import fastifyCookie from '@fastify/cookie';
import fastifyCors from "@fastify/cors";
import fastifyEnv from "@fastify/env";

import {  
  corsOptions,
  envOptions,
  rateLimitOptions,
  fastifySessionOptions, 
} from "@config/fastifyServerConfig";

import prismaPlugin from "@customPlugins/prismaPlugin";

import Routes from './Routes';

const fastify = Fastify({
  logger: { transport: { target: 'pino-pretty', options: { translateTime: 'dd/mm/yyyy HH:MM:ss Z' } } },
  ignoreTrailingSlash: true,
  trustProxy: true,
  bodyLimit: 1024 * 1024 * 1, // 1MB limit for body
});

async function fastifyRegister() {
  await fastify.register(fastifyEnv, envOptions);
  fastify.log.info('envOptions loaded');

  await fastify.register(fastifyRateLimit, rateLimitOptions(fastify));
  fastify.log.info('rateLimitOptions loaded');

  await fastify.register(fastifyCors, corsOptions);
  fastify.log.info('corsOptions loaded');

  await fastify.register(fastifyCookie);
  fastify.log.info("fastifyCookie loaded");

  await fastify.register(fastifySession, fastifySessionOptions);
  fastify.log.info("fastifySession loaded");

  await fastify.register(prismaPlugin);
  fastify.log.info('Prisma registered');

  await fastify.register(new Routes().handle, { prefix: '/api' } as FastifyRoutesOptions);
  fastify.log.info('Routes Registered');

  return fastify;
}

export default fastifyRegister;``` code

**Comment by HellpMe** [comment]
I did other tests and managed to "find" the problem, but it's still not "clear" in the fastify@cookie that needs the fastify@session itself, and I opened the issues in the wrong repo :p, but anyway, it's already something that could be updated in mind as fastify-session has been deprecated for some time now.

**Comment by Uzlopak** [comment]
What do you mean? We have changed the namespace of the fastify packages from fastify-session to @fastify/session.

**Comment by HellpMe** [comment]
No in the dependencies before migration to @fastify/item, at least the fastify-cookie/fastify-session, it doesn't matter that they are already deprecated
