### ISSUE TITLE
CookieSerializeOptions option sameSite description typo

### ISSUE THREAD

**Issue by Mihai-MCW** [fastify/fastify-cookie#235]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

There is a typo in [fastify-cookie/typesplugin.d.ts](https://github.com/fastify/fastify-cookie/blob/37bd8409c0d99ee9558f7f485edc56b5bcd1d696/types/plugin.d.ts#L121). 

I believe it should be saying **none**:
/** A `boolean` or one of the `SameSite` string attributes. E.g.: `lax`, `none` or `strict`.  */
Rather than **node**:
/** A `boolean` or one of the `SameSite` string attributes. E.g.: `lax`, `node` or `strict`.  */

**Comment by Uzlopak** [comment]
that is true. can you provide a PR please?

**Comment by gurgunday** [comment]
This can be closed.
