### ISSUE TITLE
How do I remove a cookie?

### ISSUE THREAD

**Issue by Exiliot** [fastify/fastify-cookie#24]
Hi,

Could you give an example please how to remove a cookie using fastify reply? Unfortunately, cannot find any methods for this action, while it is quite needed, especially for "httpOnly" cookies.

Thank you in advance!

**Comment by cemremengu** [comment]
I think you can (re)set it with an older expiration date like `Date.now()` ?

**Comment by jsumners** [comment]
Correct. As per spec you simply set a new cookie with the same name and an expired lifetime.

**Comment by Exiliot** [comment]
Great, thank you for the answers!
