### ISSUE TITLE
ESM imports are failing

### ISSUE THREAD

**Issue by gajus** [fastify/fastify-cookie#253]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

N/A

### Plugin version

9.0.4

### Node.js version

19.9.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

13.2.1

### Description

Importing in ESM workspace is failing with an error:

```ts
import { fastifyCookie } from '@fastify/cookie';
         ^^^^^^^^^^^^^
SyntaxError: Named export 'fastifyCookie' not found. The requested module '@fastify/cookie' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@fastify/cookie';
const { fastifyCookie } = pkg;
```

### Steps to Reproduce

Add `"type": "module"` to `package.json`.

### Expected Behavior

Should work with ESM imports.

**Comment by gurgunday** [comment]
There isn’t a named export called fastifyCookie

**Comment by gurgunday** [comment]
import pkg from '@fastify/cookie';
const { fastifyCookie } = pkg;

should work

**Comment by gajus** [comment]
But that fails TypeScript types.

**Comment by gajus** [comment]
For context, `const { fastifyCookie } = await import('@fastify/cookie')` works as expected.

**Comment by gurgunday** [comment]
> For context, const fastifyCookie = await import('@fastify/cookie') works as expected.

If you're looking for the equivalent of this import, it would be the following:

```js
import fastifyCookie from '@fastify/cookie';
```

It uses default exports - notice how there aren't curly brackets (`{}`)

**Comment by gajus** [comment]
Ah, misread the error indicators in VSCode.

```ts
import fastifyCookie from '@fastify/cookie';
```

The error is coming from ESLint:

```
Using exported name 'fastifyCookie' as identifier for default export.eslint[import/no-named-as-default](https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/no-named-as-default.md)
```

https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/no-named-as-default.md

i.e. Looks like ESLint thinks that there is `fastifyCookie` named export, but there isn't.

**Comment by gajus** [comment]
I can only assume that this is because of:

```
export const fastifyCookie: FastifyCookie;
```

which exists inside of the `namespace fastifyCookie`.

I am not familiar with TypeScript namespaces, so cannot comment whether this is an issue with this package or ESLint rule.

**Comment by Uzlopak** [comment]
According to the eslint rule, this is a warning for you as an end user, as it could be that you wanted to use the named import and not the default import. Nothing to with us.

**Comment by gajus** [comment]
But there is no named export.

**Comment by Uzlopak** [comment]
https://github.com/fastify/fastify-cookie/blob/290e559f46b49f0b55bea858fccb27c67db9c259/plugin.js#L214

**Comment by gajus** [comment]
So that takes us to the original issue.

```ts
import { fastifyCookie } from '...'
```

Does not work

**Comment by Uzlopak** [comment]
Please provide a repo

**Comment by gurgunday** [comment]
> https://github.com/fastify/fastify-cookie/blob/290e559f46b49f0b55bea858fccb27c67db9c259/plugin.js#L214

That will not work if that was the intention. To do an ESM named export, a property of `module.exports` must be set like so: `module.exports.fastifyCookie = fastifyCookie`

I haven't properly looked at the code but ESLint might be mistakenly thinking that a named export exists while it doesn't. Why do you import it like that anyway? This is the de-facto way of registering plugins/routes:
```js
// await is optional *here*
await fastify.register(import("@fastify/cookie"), {
});
```
