### ISSUE TITLE
unsignCookie not fired on event 'onRequest' in NestJs context

### ISSUE THREAD

**Issue by johaven** [fastify/fastify-cookie#266]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

9.2.0

### Node.js version

20.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

Using NestJs (10.x) and the Fastify adapter to register fastify-cookie as described here: https://docs.nestjs.com/techniques/cookies#use-with-fastify, the cookie is signed fine but it is not unsigned when receiving requests.

### Steps to Reproduce

**Nest Bootstrap**
...
```typescript
import fastifyCookie from '@fastify/cookie'
...
const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter({ logger: false }), { bufferLogs: true })
await app.register(fastifyCookie, { secret: configService.get('server.secret') })
...
```
**Route Conf**
```typescript
@Get('login')
  async login(@Request() req: FastifyRequest | any, @Res({ passthrough: true }) res: FastifyReply) {
    res.cookie('access_token', payload, {
      path: '/',
      httpOnly: true,
      sameSite: 'lax',
      maxAge: 900000,
      signed: true,
      secure: false
    })
    return { status: 'ok' }
  }
```
**Passport JwtStrategy (in Cookie)**
```typescript
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor(private readonly configService: ConfigService) {
    super({
      jwtFromRequest: ExtractJwt.fromExtractors([JwtStrategy.extractJWTFromCookie, ExtractJwt.fromAuthHeaderAsBearerToken()]),
      ignoreExpiration: false,
      secretOrKey: configService.get<string>('server.secret')
    })
  }
...
private static extractJWTFromCookie(req: FastifyRequest | any): string | null {
    // used to check jwt token stored in cookie
    if (req.cookies && req.cookies.access_token) {
      console.log('original', req.cookies.access_token) // should be unsigned but not
      // content : original eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzOTU5OTgsImV4cCI6MTcwMTM5Njg5OH0.nIpIYW0l89dibQJ8pLl0yHLFsleuEYaLjTaI7BjzM1s.OdsJbNqa7AR8rluFMqRJvBc7etIIgQLd4hg3rfspB2Y

      console.log('unsigned', req.unsignCookie(req.cookies.access_token).value) // unsigned and right
     // content: unsigned eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEzOTU5OTgsImV4cCI6MTcwMTM5Njg5OH0.nIpIYW0l89dibQJ8pLl0yHLFsleuEYaLjTaI7BjzM1s

      // the content here should be **req.cookies.access_token**
      return req.unsignCookie(req.cookies.access_token).value
    }
    return null
  }
```

### Expected Behavior

The 'onRequest' hook doesn't seem to be triggered (assumption) or the deserialization isn't happening at the right time but the cookie should be unsigned.

**Comment by climba03003** [comment]
Can you provide a reproducible code without `NestJS`?
We do not provide support for `NestJS`.

**Comment by johaven** [comment]
I'm not sure if there is a link with NestJS, in your _parseCookies_ / _parseCookie_ functions I don't see any attempt to unsigned cookies.

So maybe this is a misunderstanding on my part, I thought that if _options.parseOptions_ contained _signed: true_, in this case we were trying to unsigned the cookie, but that doesn't seem to be the default behavior :)

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](https://discord.gg/NestJS) channel (support) for such questions.

**Comment by johaven** [comment]
Perhaps it would be wiser in this case to ask Nest Support not to include you in their documentation (https://docs.nestjs.com/techniques/cookies#use-with-fastify)

**Comment by mcollina** [comment]
Nest has a company behind it. Fastify is a project driven by volunteers. They also have a (paid) support plan. https://enterprise.nestjs.com/
