### ISSUE TITLE
Missing priority option.

### ISSUE THREAD

**Issue by linkthai** [fastify/fastify-cookie#274]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Plugin version

9.3.0

### Node.js version

20.5.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Sonoma

### Description

The priority options was removed in 9.2.0, and the cookies are defaulted to priority Medium now.

https://github.com/fastify/fastify-cookie/commit/9e4652ff303c9b1c4581c36a86d37b026a767bc4

### Steps to Reproduce

``` ts 
reply.cookie(
      AUTH_COOKIE,
      JSON.stringify({
        accessToken,
        refreshToken,
        metadata,
        refreshTokenExpiresAt,
      }),
      {
        maxAge: new Date(refreshTokenExpiresAt).getTime() / 1000,
        httpOnly: true,
        sameSite: 'none',
        priority: 'high', <--- causing type error
      },
    );```

### Expected Behavior

The priority options have typings and it works.

**Comment by gurgunday** [comment]
The type was there but I couldn’t find the real code, and assumed it didn’t exist, I’ll take another look

**Comment by gurgunday** [comment]
Seems like that option didn’t _really_ exist for a while now

I don’t see Priority defined in RFC 6265 either

Do you really need it?

**Comment by linkthai** [comment]
> Seems like that option didn’t really exist for a while now

Is it? In the 9.1.0, the cookie I created could use priority High and the cookie is actually on top of the cookie list. In the 9.3.0, the cookie is always Medium in the middle of the list.

I'm not sure if it 100% neccessary, but it's my authentication cookie. If I have an option to make its priority as high as I could I  would do it. 

I'm not acknowledged about RFC requirements, but Priority is an actual mechanism that is used by current browsers. And there is no mention or indication that they were deprecated, I can't find them anywhere (!). So I don't see why it was removed when it still being implemented by the browsers.

**Comment by climba03003** [comment]
The PR that removed the priority is https://github.com/fastify/fastify-cookie/pull/260 which we change from `cookie` to our own implementation.

**Comment by gurgunday** [comment]
I vote on keeping the fork

**Comment by mcollina** [comment]
I think we should keep the fork at this point. We have been adding it back every now and then because of the slow responsiveness of `cookie` and unless we see some change there, I expect we would need to fork again in the future.

**Comment by Uzlopak** [comment]
Created PR #275
