### ISSUE TITLE
The unit for maxAge in the setCookie options is incorrect

### ISSUE THREAD

**Issue by winverse** [fastify/fastify-cookie#279]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.18

### Plugin version

9.3.1

### Node.js version

18.17

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

ventura 13.6.3

### Description

Before you read on, please refer to the [previous issue](https://github.com/fastify/fastify-cookie/issues/219)!

It seems that in the previous pull request, the time unit for maxAge was changed to seconds in the explanation. However, in both versions 8.3.0 and 9.3.1, it is still in milliseconds, not seconds, so it didn't work as intended.

### Steps to Reproduce

login process
```js
        this.cookie.setCookie(reply, 'access_token', tokens.accessToken, {
          maxAge:  60 * 60 * 24 // working
          // maxAge: 1000 * 60 * 60 * 24, // not working
        })
        this.cookie.setCookie(reply, 'refresh_token', tokens.refreshToken, {
          maxAge:  60 * 60 * 24 * 30, // working
          // maxAge: 1000 *  60 * 60 * 24 * 30, // not working
        })
```

cookie class
```js 
  public setCookie(
    reply: FastifyReply,
    name: string,
    value: string,
    options?: CookieSerializeOptions,
  ): void {
    this.domains.forEach((domain) => {
      reply.cookie(name, value, {
        httpOnly: true,
        domain,
        path: '/',
        ...options,
      })
    })
  }
  ```

result (unit: seconds)
![스크린샷 2024-02-20 오전 7 29 02](https://github.com/fastify/fastify-cookie/assets/40335396/09629dd4-6fa7-42b3-875d-89c2fd9a6f42)

result (unit: milliseconds)
![스크린샷 2024-02-20 오전 7 50 01](https://github.com/fastify/fastify-cookie/assets/40335396/008cefd4-9093-4730-be5e-9e9030e5b9e5)

### Expected Behavior

It seems necessary to reapply [this pull request](https://github.com/fastify/fastify-cookie/pull/220)

**Comment by winverse** [comment]
I'm sorry, it turns out that this issue is actually working fine in version 9.3.1, so self close this issue

**Comment by Uzlopak** [comment]
reapply or revert?

**Comment by winverse** [comment]
The previous pull request was applied in version 8.3.0, where the unit was milliseconds. However, in version 9.3.1, the unit is correctly set to seconds, so there's no need for any changes! I'll close this issue. Thank you.
