### ISSUE TITLE
Cannot use .setCookie when using plugin with NestJS

### ISSUE THREAD

**Issue by vinnivitz** [fastify/fastify-cookie#281]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

9.3.1

### Node.js version

20.9.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

6.6.16-2-MANJARO

### Description

I have Nestjs (version 10.3.3) with the fastify adapter and passportjs (version 0.7.0).

this is my main.ts file:

```
import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';

import { AppModule } from './app.module';
import { ConfigService } from '@nestjs/config';
import fastifyCookie from '@fastify/cookie';

async function bootstrap() {
	const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
	const configService = app.get(ConfigService);
	const port = configService.get<number>('PORT');
	const secret = configService.get<string>('COOKIE_SECRET');
	app.useGlobalPipes(new ValidationPipe());
	await app.register(fastifyCookie, { secret });
	await app.listen(port);
}
bootstrap();
```
 and this is my controller file:
 
```
import { Body, Controller, Get, Param, Post, Req, Res, UseGuards } from '@nestjs/common';
import { Request } from 'express';

import { LocalGuard } from './guards';
import { UserModel } from './models';
import { FastifyRequest, FastifyReply } from 'fastify';

@Controller('auth')
export class AuthController {
	constructor(private authService: AuthService) {}

	@Post('login')
	@UseGuards(LocalGuard)
	login(@Req() req: Request, @Res() response: FastifyReply) {
		response.setCookie()
	}
}
```

but for `response.setCookie()` it says: Property 'setCookie' does not exist on type 'FastifyReply<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, RouteGenericInterface, unknown, FastifySchema, FastifyTypeProviderDefault, unknown>'.ts(2339)

I already tried to research but i didnt found anything. what do i miss?

### Steps to Reproduce

- setup nestjs 
- add fastify-adapter
- add @fastify/cookie plugin
- add contoller and try to access `.setCookie` method from FastifyReply type

### Expected Behavior

being able to access `.setCookie` method via the FastifyReply type

**Comment by climba03003** [comment]
Please isolate the problem to `fastify` only.
We offer no helps on `nestjs` related problem.
