### ISSUE TITLE
Why is there automatic cookie signing?

### ISSUE THREAD

**Issue by gabor-s** [fastify/fastify-cookie#287]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

If I set a cookie with `setCookie` and I configured this plugin with `signed: true` then the cookie will be automatically signed. However when I read the cookie there's no automatic unsigning, I have to do it manually by calling `unsignCookie`.
What is the reasoning behind this imbalanced behavior?

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by gurgunday** [comment]
It's because in other parts of an application you might have `signed: false` and it would hurt performance to try to unsign every potential cookie
