### ISSUE TITLE
Plugin is being listed as "fastify-cookie" instead of "@fastify/cookie" in the dependency list. Is this intended behavior?

### ISSUE THREAD

**Issue by fidalgobr** [fastify/fastify-cookie#288]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi. I am facing an assetion error with fastify/session because the fastify/cookie plugin is being registered as "fastify-cookie" instead of "@fastify/cookie":  

The first line of code is the array of dependencies being logged. The remaining are error information.
![image](https://github.com/fastify/fastify-cookie/assets/82066907/843822b2-09f7-493b-b83a-b517cc1fb966)

I would just like to know if this is intended behavior or if this is a bug so I know where to report this issue. Thank you very much!

**Comment by mcollina** [comment]
You should use `@fastify/cookie`. `fastify-cookie` is an older version of this we renamed.

**Comment by fidalgobr** [comment]
> You should use `@fastify/cookie`. `fastify-cookie` is an older version of this we renamed.

![image](https://github.com/fastify/fastify-cookie/assets/82066907/e7c11567-37c1-4ae2-8bab-018cf8532ba1)
Unfortunately I am already using @fastify/cookie

**Comment by fidalgobr** [comment]
I reinstalled the module and removed a "fastify-cookie" module that was installed, probably was causing the issue with conflicting names. Thank you!
