### ISSUE TITLE
Should a secret be user-specific or site-wide?

### ISSUE THREAD

**Issue by U-4-E-A** [fastify/fastify-cookie#297]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The documentation does not specify this or make a recommendation.

My plan is to have a site-wide array or secrets stored in a microservice (therefore not in the server/app or the DB). Every X weeks/months a new secret will be pushed to the array and the oldest secret removed. This will be done in a way so that there will be a valid secret for unsigning as long as the max-age of the session is not breached.

Thanks.

**Comment by jsumners** [comment]
That is up to your application design.
