### ISSUE TITLE
Version 9.4.0 is not the latest on NPM

### ISSUE THREAD

**Issue by yurtaev** [fastify/fastify-cookie#298]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

![CleanShot 2024-08-20 at 12 34 16](https://github.com/user-attachments/assets/3a439f52-0c69-4781-8721-218ab28eff8f)

**Comment by climba03003** [comment]
Fixed
