### ISSUE TITLE
clearCookie does not include maxAge, neither allows to pass it as options

### ISSUE THREAD

**Issue by aristofun** [fastify/fastify-cookie#303]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0

### Plugin version

v10.0.1

### Node.js version

any

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

any

### Description

These are the problematic lines:

https://github.com/fastify/fastify-cookie/blob/ccb90539af657184c07dae983db5bdb7afa8617e/plugin.js#L42-L46

Without `maxAge: 0` at least some of cookie jar implementations (for example https://www.npmjs.com/package/tough-cookie) keep actual cookie with empty value in the storage instead of deleting them (like they do when `maxAge` is set to zero).

Because of this flaw some users had to come up with workarounds [like this](https://github.com/fastify/fastify-secure-session/blob/d322f37b46e911c6a091ff90f20900dd9e1988da/index.js#L278-L284).

### Expected Behavior

`maxAge` should be set along with `expires` option

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by gurgunday** [comment]
[Latest RFC](https://www.rfc-editor.org/rfc/rfc6265.html) says:

> Finally, to remove a cookie, the server returns a Set-Cookie header
   with an expiration date in the past.  The server will be successful
   in removing the cookie only if the Path and the Domain attribute in
   the Set-Cookie header match the values used when the cookie was
   created.

We return `new Date(1)`, which is `Thu Jan 01 1970 01:00:00`

Our implementation is correct

**Comment by aristofun** [comment]
> Our implementation is correct

Adding `maxAge` would not make it less correct, isn't it?

Yet it would improve devX for many users.

**Comment by aristofun** [comment]
https://github.com/fastify/fastify-cookie/pull/304
