### ISSUE TITLE
bug: issue with quotes around string values in 11.0.1

### ISSUE THREAD

**Issue by gabrielcsapo** [fastify/fastify-cookie#307]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Plugin version

11.0.1

### Node.js version

22.2.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.7.1

### Description

There seems to be an issue utilizing the new cookie library where cookie values are getting an additional quote around the value

# 10.0.1

<img width="515" alt="Screenshot 2024-11-19 at 2 25 30 PM" src="https://github.com/user-attachments/assets/b39664da-e033-439a-8ceb-f6fbfb52a1ac">

# 11.0.1

![Screenshot 2024-11-19 at 2 17 30 PM](https://github.com/user-attachments/assets/ce6bef32-95af-4a06-9278-d1fbba496717)

### Expected Behavior

expected behavior would be the result of 10.0.1

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Eomm** [comment]
I wonder if it is related to: https://github.com/fastify/fastify/blob/main/docs/Guides/Migration-Guide-V5.md#usesemicolondelimiter-false-by-default

**Comment by mcollina** [comment]
Looking at our tests, I don't see how that would happen, so I would recommend if you could add a way for us to easily reproduce this.

**Comment by jsumners** [comment]
Please provide an example request, using [curl](https://curl.se), that shows how to replicate this issue.

**Comment by gurgunday** [comment]
It's not adding quotes, it's just not removing them if something has already added them I believe

The RFC doesn't talk about quote removal so it was removed in the v1 of the `cookie` package

So it's probably related to this: https://github.com/jshttp/cookie/pull/180

If so, we might add an option (off by default), that brings this functionality back, or if you are using another Fastify core package that is causing this, let us know and we might remove the quotes there
