### ISSUE TITLE
Property 'setCookie' does not exist on type 'FastifyReply<ServerResponse>'.

### ISSUE THREAD

**Issue by colinmcparland** [fastify/fastify-cookie#38]
Installed `fastify-cookie` with `npm install fastify-cookie`.  
Using VSCode.  
fastify v.2.0.1
fastify-cookie v.3.0.2
error:
```
{
	"code": "2339",
	"message": "Property 'setCookie' does not exist on type 'FastifyReply<ServerResponse>'.",
	"source": "ts",
}
```

Code:

```ts
const fastifyCookie = require("fastify-cookie");
export const renderMiddleware = (fastify: FastifyInstance) => {
    fastify.register(fastifyCookie);
    fastify.post("/create-session-cookie", async (req, res) => {
       
        try {
            const sessionCookie = await thriftClient.createSession(
                "blabla",
                tokenExpDate,
                lastIp,
                tokenData,
                null
            );

            res.setCookie("sessionId", sessionCookie.sessionId, {}) < Throws error
                .status(200)
                .send(sessionCookie);
        } catch (e) {
            req.log.info(JSON.stringify(e));
            res.status(500).send(e);
            return;
        }
    });
}
```

**Comment by mcollina** [comment]
Would you like to send a PR to fix this?

**Comment by colinmcparland** [comment]
Sure, would you mind pointing me in the right direction? :^)

**Comment by mcollina** [comment]
I don't know why it's not picked up correctly.
Maybe @Ethan-Arrowood @evanshortiss might help.

**Comment by evanshortiss** [comment]
@colinmcparland can you try using import syntax instead? This works for me:

```ts
import * as fastifyCookie from "fastify-cookie";
import { FastifyInstance } from 'fastify'

export const renderMiddleware = (fastify: FastifyInstance) => {
    fastify.register(fastifyCookie);
    fastify.post("/create-session-cookie", async (req, res) => {
        const cookie = 'not a real cookie'

        res.setCookie("sessionId", cookie, {})
            .status(200)
            .send(cookie);
    });
}
```

**Comment by evanshortiss** [comment]
@colinmcparland if that fails, let us know which versions you're using for `fastify`, `fastify-cookie` and `typescript` in your project, plus tsconfig/compile flags.

**Comment by evanshortiss** [comment]
@colinmcparland I got more time to look into this and see the *real* issue. 

Change:

```js
const fastifyCookie = require("fastify-cookie");
```

to this:

```ts
import fastifyCookie = require("fastify-cookie");
```

Import will make TS import the typings.

**Comment by colinmcparland** [comment]
@evanshortiss amazing, that fixed the issue.  Thanks!!

**Comment by arielnmz-iws** [comment]
Can we reopen this? Wether I use

    import fastifyCookie = require("fastify-cookie");

Or 

    import * as fastifyCookie from "fastify-cookie";

tsc complains about `error TS2769: No overload matches this call.`

Moreover, using `require` breaks ES6 modules

**Comment by evanshortiss** [comment]
@arielnmz-iws this works for me with a default `tsconfig.json` generated using `tsc --init` and TypeScript 4.2.3:

```ts
import { FastifyCookieOptions } from 'fastify-cookie'
import cookie from 'fastify-cookie'
import fastify from 'fastify'

const app = fastify()

app.register(cookie, {
    secret: "my-secret", // for cookies signature
    parseOptions: {}     // options for parsing cookies
} as FastifyCookieOptions)
```

**Comment by arielnmz** [comment]
I have been postponing this for very long, sorry, the only way I have been able to make this work is by pinning `pnpm` to verson `6.16.0` any newer version fails with the error in the OP (weird, the pnpm version seems to keep this stable, but what does the package manager have to do with this?). I will try to reproduce it in a test repo as this seems to only happen when used in combination with other plugins. This does not happen when using ONLY this plugin. Perhaps this has to be escalated to the fastify project?

**Comment by shunkica** [comment]
I have the same problem. Was this fixed?

`TS2339: Property 'setCookie' does not exist on type 'FastifyReply<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>'.`


```
"@nestjs/platform-fastify": "^8.4.5",
"fastify": "^3.29.0",
"fastify-cookie": "^5.7.0",
"typescript": "^4.7.2",
```

**Comment by LuckyArdhika** [comment]
fastify 4.22.2 still get this error

**Comment by gurgunday** [comment]
Can you give an example to help me debug the issue?

**Comment by LuckyArdhika** [comment]
Guys, i has been fix it in my project. By default, typescript compile type by normal path, but im using pnpm which create symlinks, nah you must setting tsconfig to preserve symlinks, 
`{
  "compilerOptions": {
    "preserveSymlinks": true,
  }
}`

**Comment by kelvin2200** [comment]
I've stumbled upon the same problem with the latest version of fastify (4.25.2 at the time of this writing) and @fastify/cookie: 9.3.1

My setup uses PNP which is known to break dependencies, so if your setup also uses PNP, the solution (at least for cookies)
is to add this to your .yarnrc file
```yml
packageExtensions:
  '@fastify/cookie@*':
    dependencies:
      'fastify': '*'
```

this is because @fastify/cookie depends on fastify and uses module augmentation to declare the `setCookie`, `clearCookie` methods and others.

This workaround should also apply to other scenarios in a PNP project. Just make sure to add required dependencies in .yarnrc
For more info, I'd suggest reading on how PNP works and why the dependency chain is broken

**Comment by ApnikaPanika** [comment]
Good evening guys, I have stumbled upon this problem now, and I can't find fix for it, I am using the latest versions of fastify and fastify/cookie. My dependencies:
` "@fastify/cookie": "^9.3.1",`

**Comment by jpenna** [comment]
I use `npm` and I get this error from time to time (every 10min roughly). The quick fix I found was toggling `tsconfi.json` -> `compilerOptions.incremental` on and off. I will try the `compilerOptions.preserveSymlinks: true` and see if it is more permanent. I will update this comment later.

**Comment by Gorthog** [comment]
using `pnpm` i faced the same problem. Adding `compilerOptions.preserveSymlinks: true` made vscode happy, but build still failed. the workaround i've found is adding in `.npmrc`

```
node-linker=hoisted
```

not happy with this workaround, as it negates some of pnpm advantages.

**Comment by Datzu712** [comment]
I'm working with prisma, but when I try to disable preserveSymlinks or the mentioned option by @Gorthog, prima's types stop working. Someone know how to fix this without breaking other things?
