### ISSUE TITLE
I see set-cookie in response headers, but cookie is not saved in browser

### ISSUE THREAD

**Issue by cryptofuture** [fastify/fastify-cookie#40]
Basically after an auth, I setting a cookie, but apparently after page refresh on the cookie that was set by cloudflare is saved And the cookie that I transmitted with set-cookie is not used in after set-cookie requests

```bash
# Response headers
HTTP/2.0 200 OK
date: Thu, 18 Jul 2019 10:03:25 GMT
content-type: application/json; charset=utf-8
content-length: 29
set-cookie: __cfduid=d578c7a5e4378dc1b1946964a08ebc4ec1563444205; expires=Fri, 17-Jul-20 10:03:25 GMT; path=/; domain=.doc.io; HttpOnly; Secure
set-cookie: __doc=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlIjoiNzQ2NTczNzQ0MDY2NjE3Mzc0NmQ2MTY5NmMyZTZkNzgiLCJwIjoiNTUzMjQ2NzM2NDQ3NTY2YjU4MzEzODMzNTU0NjUwNTU2ZjRiMzkzMTY3NDUzNDY5NDc3MzM3MzgzOTU5MzczMDUxNjk0ZjQxNjQ0OTM5Nzg0YjZiNzU1Njc3Nzk0NDc0NjE3NDMxNTE0NzcwMzE0YjQxNmY1MjU5MzM3YTZhNDU2NDJiNmU0ZTc0NGE3NTMyNTQ1ODc2NjI1YTczNDc1MTQ1Njc0MjVhNGQ0MTNkM2QiLCJkIjoiMzEzNTM2MzMzNDM0MzQzMjMwMzUzNTM2MzMiLCJpYXQiOjE1NjM0NDQyMDV9.go1jDpc2rBe5FjK2sKX4ybW4PhCPFq1xT1WIX-mSI84; Domain=.doc.io; Path=/; Expires=Thu, 18 Jul 2019 16:03:25 GMT; HttpOnly; Secure
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4f83a02a3dc36455-FRA
X-Firefox-Spdy: h2
```
```js
reply
.code(200)
.header('Access-Control-Allow-Origin', '*')
.header('Content-Type', 'application/json; charset=utf-8')
.setCookie('__doc', token, {
domain: '.doc.io',
path: '/',
secure: true,
httpOnly: true,
expires: new Date(new Date().setHours(new Date().getHours() + 6))})
.send({ 'success': 'Sign In success' })
```

All my websites are https

First I do POST request for an auth on `/auth`, and you could see response in response headers above and after I do GET on (trying to load page) from `/page` and get cookies, but with `reply.log.info(request.cookies)` I see only cookies from cloudflare. Surely I tried to refresh and go to address in different table, there just no any cookies, but from cloudflare.

```bash
# Request headers
Host: test.doc.io
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Cookie: __cfduid=d578c7a5e4378dc1b1946964a08ebc4ec1563444205
Upgrade-Insecure-Requests: 1
TE: Trailers
```

P.S.: I removed `httpOnly: true` as it seems shouldn't work for json request types, however that changes nothing

Any idea?

**Comment by jsumners** [comment]
If you are seeing the header in the response at your client, but not in the request from the client, then the plugin is working correctly while the client is not. This is usually due to conflicts with the path and what the browser thinks the domain actually is. I would remove cloudflare from the equation to properly diagnose the problem.

**Comment by cryptofuture** [comment]
Now I'm, really confused as it seems it works in Chromium, but not works in Firefox even with new clear profile

**Comment by cryptofuture** [comment]
Hmm after I tested it with an actual page with js code for a XHR request it works fine. However cookie was only displayed, but not actual saved in the storage when I was sending request directly in Firefox's inspector. Srly lost a day to figure out created in inspector cookies seems preventing from installing
