### ISSUE TITLE
Allow passing "secret" as part of the `setCookie` and `getCookie` decorators

### ISSUE THREAD

**Issue by iMoses** [fastify/fastify-cookie#51]
If you like the idea I'll have a PR ready in no time :)

## 🚀 Feature Proposal

Allow passing "secret" as part of the `setCookie` and `getCookie` decorators, not just at the plugin's initialization.

## Motivation

Allow the usage of multiple secrets according to application's logic. 

One example is using a different secret per logged in user.

## Example

Usage example:
```js
fastify.get('/', (req, reply) => {
  const aCookieValue = req.cookies.cookieName
  const bCookieValue = reply.unsignCookie(req.cookies.cookieSigned, 'my-secret');
  reply
    setCookie('bar', 'bar', {
      path: '/',
      signed: true,
      secret: 'my-secret'
    })
    .send({hello: 'world'})
})
```

Changes to code:
```js
value = cookieSignature.sign(value, opts.secret || secret)  // line: 14
```
```js
// lines: 59-61
fastify.decorateReply('unsignCookie', function unsignCookieWrapper (value, secretOverride) {
  return cookieSignature.unsign(value, secretOverride || secret)
})
```

**Comment by mcollina** [comment]
Go for it!
Il 1 gen 2020, 03:33 +0200, iMoses <notifications@github.com>, ha scritto:
