### ISSUE TITLE
If no cookie header is set, cookies are preserved from previous request 

### ISSUE THREAD

**Issue by iMoses** [fastify/fastify-cookie#53]
## 🐛 Bug Report

In case my user clears all of his cookies, this condition will not execute:
```js
    const cookieHeader = fastifyReq.req.headers.cookie
    if (cookieHeader) {
      fastifyReq.cookies = cookie.parse(cookieHeader, options)
    }
```

and `fastifyReq.cookies` is gonna remain the same as it was in the previous request.

## To Reproduce

Set a cookie and make a request, then clear all of your browser cookies and examine `req.cookies` on the next request.

## Expected behavior

Cookies decorator should reset on each request.

```js
    const cookieHeader = fastifyReq.req.headers.cookie
    fastifyReq.cookies = cookieHeader ? cookie.parse(cookieHeader, options) : {}
```

**Comment by Eomm** [comment]
The `request.cookies` is created empty at every request already.

Could you provide a complete example?

This, for example, works as expected:
```
const fastify = require('fastify')()
fastify.register(require('fastify-cookie'))

fastify.get('/', (req, reply) => {
  reply.send(req.cookies)
})

fastify.listen(8080)

// curl -H 'cookie:hello=world' http://localhost:8080/
// {"hello":"world"}
// curl -H 'cookie:' http://localhost:8080/
// {}
// curl http://localhost:8080/
// {}
```

**Comment by iMoses** [comment]
@Eomm You are correct, it seems that the problem comes from my pattern of set a cookie then manually adding the value to the cookies object at the `preHandler` hook, so that routes and middleware could access it.

If no cookie header was sent then the default object is returned, which should be empty, but if it changed during any of the requests then the default result will always be that changed object.

Try this:
```
const fastify = require('fastify')()
fastify.register(require('fastify-cookie'))

fastify.get('/', (req, reply) => {
  reply.send(req.cookies)
})

fastify.addHook('preHandler', async req => {
  if (!req.cookies.rand)
    req.cookies.rand = Math.random()
});

fastify.listen(8080)
```

**Comment by Eomm** [comment]
Oh, I didn't know an object in a decorated request wasn't isolated.
I understand the problem: all the requests have a pointer to the same `{}` and if you don't set all the fields for each, you will have this issue.

Did you know it @mcollina ?

```js
const fastify = require('fastify')()
fastify.register(require('fastify-cookie'))

fastify.decorateRequest('foo', {})

fastify.get('/', (req, reply) => {
  reply.send({ ...req.cookies, ...req.foo })
})

fastify.addHook('preHandler', async req => {
  if (!req.cookies.rand) {
    req.cookies.rand = Math.random()
  }
  if (!req.foo.ts) {
    req.foo.ts = Date.now() // set it for all the requests
  }
})

fastify.listen(8080)
```

I would wait for tips before solving this bug because I'm undecided if we should apply to fastify core or simply add the missing `else` in the code you spotted (or both as well 🤯)

**Comment by mcollina** [comment]
Fastify behavior is totally expected. This plugin should use a hook to reset that object to a different value for every request (or possibly set it only if there are cookies).

**Comment by jsumners** [comment]
https://github.com/fastify/fastify-cookie/releases/tag/v3.4.1
