### ISSUE TITLE
CookieSerializeOptions.sameSite should support "none" value

### ISSUE THREAD

**Issue by stephan9mertel** [fastify/fastify-cookie#61]
## 🐛 Bug Report
The CookieSerializeOptions at https://github.com/fastify/fastify-cookie/blob/master/plugin.d.ts don't allow to set the `sameSite` parameter to `"none"`

## Expected behavior
Allow `sameSite` to be `"none"`, as specified in https://www.npmjs.com/package/cookie#options-1

## Your Environment
- *node version*: 10.8.0
- *fastify version*: 2.10.0
- *fastify-cookie version*: 3.4.1
- *os*: Linux

**Comment by mcollina** [comment]
would you mind to send a PR? Thanks!
Il 13 gen 2020, 13:25 +0100, stephan <notifications@github.com>, ha scritto:

**Comment by stephan9mertel** [comment]
@mcollina here you go https://github.com/fastify/fastify-cookie/pull/62
