### ISSUE TITLE
FastifyCookieOptions type is empty

### ISSUE THREAD

**Issue by moltar** [fastify/fastify-cookie#68]
## 🐛 Bug Report

https://github.com/fastify/fastify-cookie/blob/ccff4eaf99694faf0461916aa07d399259114772/plugin.d.ts#L72

FastifyCookieOptions type is empty, while docs mention a few options, like `secret`, and `parseOptions`.

## To Reproduce

See link above.

## Expected behavior

To have options defined.

**Comment by mcollina** [comment]
Would you like to send a PR to fix this?
