### ISSUE TITLE
Property 'cookies' does not exist on type FastifyRequest

### ISSUE THREAD

**Issue by ProgrammingLife** [fastify/fastify-cookie#70]
My simplified code is: 
```js
import fastify from './git/fastify'
import fastifyCookie from './git/fastify-cookie'
const server = fastify();
server.register(fastifyCookie).after( () => {
	server.get("/ping", async (request, reply) => {
		const cookies = request.cookies; // Property 'cookies' does not exist on type 'FastifyRequest<Server, IncomingMessage, RequestGenericInterface>'
		reply.clearCookie('foo'); // Property 'clearCookie' does not exist on type 'FastifyReply<Server, ServerResponse, unknown>'
	});
});
```

Where I have two errors:

> - Property 'cookies' does not exist on type 'FastifyRequest<Server, IncomingMessage, RequestGenericInterface>'
> - Property 'clearCookie' does not exist on type 'FastifyReply<Server, ServerResponse, unknown>'

I just followed by: https://github.com/fastify/fastify-cookie
Why it doesn't work?

- *node version*: 13
- *fastify version*: 3.0
- *fasify-cookie version*: 3.6.0
- *os*: Linux

**Comment by ProgrammingLife** [comment]
Is this because: "fastify-cookie v3 only supports Fastify@2"? When Fastify-cookie v3 will support Fasity v3?

**Comment by mcollina** [comment]
We are in the process of releasing all of those modules for the upcoming v3 release. It’ll take a few weeks, use previous versions.
