### ISSUE TITLE
Validation of cookies

### ISSUE THREAD

**Issue by Zaseth** [fastify/fastify-cookie#73]
Hello! I'm using fastify-cookie for my project to work with cookies and I have a question about the route validation. Is it possible to express in a schema to specific what exact cookie should be in the cookie header?

What I want: we have the header 'cookie' that must exist, where the cookie name 'id' must exist and be typof number.

As of now, I can only specify that the header 'cookie' must exist, but sadly I don't know if it's possible to check for certain keys in such header and I was wondering if this is possible or not.

Thank you!

**Comment by jsumners** [comment]
I would use a `preValidation` or `preHandler` hook to do that.

**Comment by Zaseth** [comment]
Okay thank you.
