### ISSUE TITLE
Allow passing signed:true to clearCookie

### ISSUE THREAD

**Issue by mnpenner** [fastify/fastify-cookie#76]
## 🐛 Bug Report

I tried setting and unsetting a cookie by storing all the options in an object:

```ts
const SESSION_COOKIE_OPTIONS: CookieSerializeOptions = {
    sameSite: 'lax',
    signed: true,
    secure: false,
    maxAge: 24*60*60*30,
    httpOnly: true,
    path: '/',
}
```

This works fine for setting:

```ts
reply.setCookie(SESSION_COOKIE_NAME, sessionKeyStr, SESSION_COOKIE_OPTIONS)
```

But throws an error when unsetting:

```ts
reply.clearCookie(SESSION_COOKIE_NAME, SESSION_COOKIE_OPTIONS)
```

> TypeError: Secret string must be provided.

If you just rip the `signed` option out in the [fastifyCookieClearCookie](https://github.com/fastify/fastify-cookie/blob/c3fca36fabf88d3b38fd24641248fa658db07878/plugin.js#L35), then it should work fine.

You should remove `maxAge` too.

## To Reproduce

Above.

## Expected behavior

No error.

## Your Environment

```
❯ yarn list --depth=0 | grep fastify
├─ fastify-cookie@4.1.0
├─ fastify-error@0.2.0
├─ fastify-oauth2@4.2.1
├─ fastify-plugin@2.3.4
├─ fastify-sensible@3.0.1
├─ fastify-warning@0.2.0
├─ fastify@3.4.1
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jsumners** [comment]
I think this is working as intended. The module is meant to be minimal. If you notice, the linked code for `fastifyCookieClearCookie` does not try to manipulate the data in any way other than to follow the spec for marking a cookie as no longer valid: setting the expiration date to an invalid date.
