### ISSUE TITLE
Deprecation warning with Fastify 3.9.0

### ISSUE THREAD

**Issue by Lalem001** [fastify/fastify-cookie#86]
## 🐛 Bug Report

Upgraded `Fastify` from 3.8.0 to 3.9.0, and the following warning shows up:

> [FSTDEP006] FastifyDeprecation: You are decorating Request/Reply with a reference type. This reference is shared amongst all requests. Use onRequest hook instead. Property: cookies

I have tracked the issue to [plugin.js#L56](https://github.com/fastify/fastify-cookie/blob/v4.1.0/plugin.js#L56)

## To Reproduce

Use fastify-cookie per documented example

## Expected behavior

No warnings

## Your Environment

- *node version*: v14.15.0
- *fastify version*: 3.9.0
- *os*: Mac

**Comment by jsumners** [comment]
I think I'd rather see the implementation use the `getter/setter` decorator feature.

**Comment by mcollina** [comment]
Setting the property to `null` would have the same effect.

**Comment by Lalem001** [comment]
Issue is resolved with release of [4.1.1](https://github.com/fastify/fastify-cookie/releases/tag/v4.1.1)
