### ISSUE TITLE
Feature cookie signing

### ISSUE THREAD

**Issue by ToonvanStrijp** [fastify/fastify-cookie#9]
I would like to see a cookie signing feature like the https://github.com/expressjs/cookie-session has.

Is that something that would be implemented in the near feature?

**Comment by jsumners** [comment]
Why not use https://www.npmjs.com/package/cookie-signature to create a signed cookie value? That's how it's done in `fastify-server-session`: https://github.com/jsumners/fastify-server-session/blob/a4b8e447f142b102a9597dc465e14af6cd2d1e18/plugin.js#L88-L89

**Comment by mcollina** [comment]
@ToonvanStrijp can you check if https://github.com/mcollina/fastify-secure-session does the trick?

**Comment by ToonvanStrijp** [comment]
@jsumners @mcollina  thanks! That's exactly what I needed!
