### ISSUE TITLE
Error ts2392 occurs in the TypeScript environment due to the wrong return type of unsignCookie

### ISSUE THREAD

**Issue by fujita-h** [fastify/fastify-cookie#93]
## 🐛 Bug Report

Error ts2392 occurs in the TypeScript environment due to the wrong return type of `unsignCookie`

## To Reproduce

```ts
const result = reply.unsignCookie(request.cookies[key])
if (result.valid) { ... }
```
Error ts2392 occurred with `result.valid`.

## Expected behavior

needs to update `plugin.d.ts`

https://github.com/fastify/fastify-cookie/blob/db367c44b9ccee5622423ee13a45ef699a713926/plugin.d.ts#L40-L42

## Your Environment

- *node version*: 14
- *fastify version*: >=3.9.2
- *os*: Linux
- *fastify-cookie*: "5.0.0"
- *typescript*: "4.1.3"

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
