### ISSUE TITLE
Add fastify.unsignCookie to be able to verify fastify.parseCookie values

### ISSUE THREAD

**Issue by cmawhorter** [fastify/fastify-cookie#99]
## 🚀 Feature Proposal

Add fastify.unsignCookie

## Motivation

#75 added fastify.parseCookie to mitigate https://github.com/fastify/fastify-websocket/issues/70 and it works, but there is no easy way to verify a signed cookie, so its usefulness is limited.

The workaround now is to create a custom signer that dupes [the default](https://github.com/fastify/fastify-cookie/blob/c3d9c984f321e5255598af4ea0b1cb5fe9d2a443/signer.js).  But that's less than ideal.

## Example

```js
// fastify-websocket handler
const signedSessionId = fastify.parseCookie(req.headers['cookie']);
const sessionId = fastify.unsignCookie(signedSessionId);
ok(sessionId.valid);
console.log('session id:', sessionId.value);
```

**Comment by mcollina** [comment]
Sure! 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Lightnet** [comment]
I didn't see any change for getting or was not update on fastify.unsignCookie(). Was testing the socket.io package.
```
function plugin (fastify, options, next) {
...
fastify.decorate('unsignCookie', function unsignCookie (value) {
    return signer.unsign(value)
  })
```
